---
- hosts: all
  tasks:

  - name: determine distrib
    command: lsb_release -sc
    register: distrib

  - name: determine kernel
    command: uname -r
    register: kernel

  - name: percona repo
    apt:
      deb: https://repo.percona.com/apt/percona-release_0.1-4.{{ distrib.stdout }}_all.deb
      state: present

  - name: install essential packages
    apt:
      name: make,qpress,netcat,socat,sysstat,mbuffer,libaio1,sysbench,lsof,percona-toolkit,linux-tools-common,linux-tools-{{ kernel.stdout }},linux-tools-{{ kernel.stdout }},python-mysqldb
      update_cache: true
      state: present

  - name: install build packages
    apt:
      name: build-essential,autoconf,libtool,gawk,alien,fakeroot,linux-headers-{{ kernel.stdout }}
      update_cache: true
      state: present

  - name: custom libgcrypt for xtrabackup binaries
    apt:
      deb: https://launchpadlibrarian.net/201289896/libgcrypt11_1.5.3-2ubuntu4.2_amd64.deb
      state: present

  - name: create directories
    file:
      path: "{{ item }}"
      owner: ubuntu
      group: ubuntu
      mode: 0755
      state: directory
    with_items:
      - /p/msb
      - /p/bkp
      - /p/bkp/stor
      - /p/bkp/work
      - /home/ubuntu/xb
      - /home/ubuntu/mysql
      - /p/bkp/r
      - /p/bkp/r/stor
      - /p/bkp/r/work

  - name: copy mysql binaries urls
    copy:
      src: files/binaries-mysql
      dest: /home/ubuntu/mysql/binaries
      mode: 0644
      owner: ubuntu
      group: ubuntu

  - name: copy xtrabackup binaries urls
    copy:
      src: files/binaries-xtrabackup
      dest: /home/ubuntu/xb/binaries
      mode: 0644
      owner: ubuntu
      group: ubuntu

  - name: upload mysql sandbox installer
    copy:
      src: files/mysql-sandbox.sh
      dest: /usr/bin/mysql-sandbox
      mode: 0755

  - name: upload sandboxes script
    copy:
      src: files/make-sandboxes.sh
      dest: /usr/bin/make-sandboxes
      mode: 0755

  - name: upload sysbench scripts
    copy:
      src: files/run-sysbench.sh
      dest: /usr/bin/run-sysbench
      mode: 0755

  - name: upload xtrabackups scripts
    copy:
      src: files/make-xtrabackups.sh
      dest: /usr/bin/make-xtrabackups
      mode: 0755

  - name: upload tests scripts
    copy:
      src: files/run-tests.sh
      dest: /usr/bin/run-tests
      mode: 0755

  - name: upload pyxbackup
    copy:
      src: ../../pyxbackup
      dest: /usr/bin/pyxbackup
      mode: 0755

  - name: upload pyxbackup test commands
    copy:
      src: files/commands-pyxbackup
      dest: /home/ubuntu/commands-pyxbackup
      mode: 0755

  - name: skeleton pyxbackup.cnf
    template:
      src: pyxbackup.cnf
      dest: /etc/pyxbackup.cnf
      mode: 0644
      owner: ubuntu
      group: ubuntu
